### ISSUE TITLE
typo in commit history

### ISSUE THREAD

**Issue by PockyJocky** [demonintherough/talent-id#1]
4b4927c237f62d59abd81861a13be89fcb435dcd
Has typo in commit message "Added a welcome age to the program" should read "Added a welcome page to the program"

**Comment by demonintherough** [comment]
Due to the age of the commit it would require a force update to be completed.  This would require that people who have already cloned this project to manually fix their local history.  Sadly the typo will remain and more care will be taken in the future.

**Comment by PockyJocky** [comment]
Thx
